CREATE TABLE if not EXISTS APARTMENT_TYPES (
	APARTMENT_TYPE_ID INT(10) NOT NULL AUTO_INCREMENT,
	APARTMENT_TYPE_TITLE VARCHAR(100),
	PRIMARY KEY (APARTMENT_TYPE_ID)
);


CREATE TABLE if not EXISTS CITIES (
	CITY_ID INT(10) NOT NULL AUTO_INCREMENT,
	CITY_NAME VARCHAR(100),
	PRIMARY KEY (CITY_ID)
);



CREATE TABLE if not EXISTS APARTMENTS (
  AP_ID INT(10) NOT NULL AUTO_INCREMENT,
	AP_NAME VARCHAR(100) NOT NULL,
	AP_DESCRIPTION VARCHAR(100) NOT NULL,
	AP_GUEST_COUNT INT(10) NOT NULL ,
	AP_COST_PER_DAY INT(10) NOT NULL ,
	AP_APARTMENT_TYPE_ID INT(10) NOT NULL ,
	AP_CITY_ID INT(10) NOT NULL,
	PRIMARY KEY (AP_ID),
  FOREIGN KEY (AP_APARTMENT_TYPE_ID) REFERENCES APARTMENT_TYPES(APARTMENT_TYPE_ID),
	FOREIGN KEY (AP_CITY_ID) REFERENCES CITIES(CITY_ID)
	 )

