CREATE TABLE if not EXISTS USERS (
  USER_ID INT(10) NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(100),
	USER_SURNAME VARCHAR(100),
	USER_EMAIL VARCHAR(50),
	USER_PASSWORD VARCHAR(100),
	 PRIMARY KEY (USER_ID)
	 )

